import { createSlice } from "@reduxjs/toolkit";
// import { iteratorSymbol } from "immer/dist/internal";

const initialState={
    cartItems:[
        {
            "image": "https://pillbox-media.s3.ap-south-1.amazonaws.com/images/1650803749927-aistock.jpeg",
            "video": null,
            "id": 7,
            "amount":1,
            "uuid": "5e5338c0-f144-4ef8-ba67-983f7f2a8fd2",
            "name": "baby product  2",
            "product_id": "",
            "price": 10,
            "discount": 1,
            "igst": 0,
            "hsn": "",
            "quantity": 10,
            "description": " description",
            "context": "",
            "composition": "",
            "packing_type": null,
            "packing_size": null,
            "schedule": null,
            "brand_id": 5,
            "status": "ACTIVE",
            "meta": {
                "usage": "",
                "about_salt": "",
                "mechanism_of_action": "",
                "pharmacokinets": "",
                "onset_of_action": "",
                "duration_of_action": "",
                "half_life": "",
                "side_effects": "",
                "contra_indications": "",
                "special_precautions": "",
                "pregnancy_related_information": "",
                "product_alchol_interaction": "",
                "old_age_related_information": "",
                "breast_feeding_related_information": "",
                "child_related_information": "",
                "indications": "",
                "interactions": "",
                "typical_dosage": "",
                "storage_requirements": "",
                "effects_mixed_dosage": "",
                "effects_overdose": "",
                "expertise_advice": "",
                "how_to_use": "",
                "faqs": []
            },
            "createdAt": "2022-04-24T12:35:50.411Z",
            "updatedAt": "2022-04-24T12:35:50.411Z",
            "deletedAt": null
        },
        {
            "image": "https://pillbox-media.s3.ap-south-1.amazonaws.com/images/1650803538840-aistock.jpeg",
            "video": null,
            "id": 6,
            "uuid": "04e033d7-47d8-46d6-8483-9e19372f0e8a",
            "name": "soap product  2",
            "product_id": "",
            "price": 10,
            "discount": 1,
            "amount":1,
            "igst": 0,
            "hsn": "",
            "quantity": 10,
            "description": " description",
            "context": "",
            "composition": "",
            "packing_type": null,
            "packing_size": null,
            "schedule": null,
            "brand_id": 5,
            "status": "ACTIVE",
            "meta": {
                "usage": "",
                "about_salt": "",
                "mechanism_of_action": "",
                "pharmacokinets": "",
                "onset_of_action": "",
                "duration_of_action": "",
                "half_life": "",
                "side_effects": "",
                "contra_indications": "",
                "special_precautions": "",
                "pregnancy_related_information": "",
                "product_alchol_interaction": "",
                "old_age_related_information": "",
                "breast_feeding_related_information": "",
                "child_related_information": "",
                "indications": "",
                "interactions": "",
                "typical_dosage": "",
                "storage_requirements": "",
                "effects_mixed_dosage": "",
                "effects_overdose": "",
                "expertise_advice": "",
                "how_to_use": "",
                "faqs": []
            },
            "createdAt": "2022-04-24T12:32:19.318Z",
            "updatedAt": "2022-04-24T12:32:19.318Z",
            "deletedAt": null
        },
        {
            "image": "https://pillbox-media.s3.ap-south-1.amazonaws.com/images/1650803451251-aistock.jpeg",
            "video": null,
            "id": 5,
            "uuid": "efd7344d-fca4-4273-afd4-41f0a3c91716",
            "name": "soap product  ",
            "product_id": "",
            "price": 10,
            "amount":1,
            "discount": 1,
            "igst": 0,
            "hsn": "",
            "quantity": 10,
            "description": " description",
            "context": "",
            "composition": "",
            "packing_type": null,
            "packing_size": null,
            "schedule": null,
            "brand_id": 5,
            "status": "ACTIVE",
            "meta": {
                "usage": "",
                "about_salt": "",
                "mechanism_of_action": "",
                "pharmacokinets": "",
                "onset_of_action": "",
                "duration_of_action": "",
                "half_life": "",
                "side_effects": "",
                "contra_indications": "",
                "special_precautions": "",
                "pregnancy_related_information": "",
                "product_alchol_interaction": "",
                "old_age_related_information": "",
                "breast_feeding_related_information": "",
                "child_related_information": "",
                "indications": "",
                "interactions": "",
                "typical_dosage": "",
                "storage_requirements": "",
                "effects_mixed_dosage": "",
                "effects_overdose": "",
                "expertise_advice": "",
                "how_to_use": "",
                "faqs": []
            },
            "createdAt": "2022-04-24T12:30:51.689Z",
            "updatedAt": "2022-04-24T12:30:51.689Z",
            "deletedAt": null
        },
        {
            "image": "https://pillbox-media.s3.ap-south-1.amazonaws.com/images/1650802649692-aistock.jpeg",
            "video": null,
            "id": 4,
            "uuid": "c02ee2ab-25eb-4dea-8e31-437f1c19c130",
            "name": "baby product  ",
            "product_id": "",
            "price": 10,
            "discount": 1,
            "amount":1,
            "igst": 0,
            "hsn": "",
            "quantity": 10,
            "description": " description",
            "context": "",
            "composition": "",
            "packing_type": null,
            "packing_size": null,
            "schedule": null,
            "brand_id": 5,
            "status": "ACTIVE",
            "meta": {
                "usage": "",
                "about_salt": "",
                "mechanism_of_action": "",
                "pharmacokinets": "",
                "onset_of_action": "",
                "duration_of_action": "",
                "half_life": "",
                "side_effects": "",
                "contra_indications": "",
                "special_precautions": "",
                "pregnancy_related_information": "",
                "product_alchol_interaction": "",
                "old_age_related_information": "",
                "breast_feeding_related_information": "",
                "child_related_information": "",
                "indications": "",
                "interactions": "",
                "typical_dosage": "",
                "storage_requirements": "",
                "effects_mixed_dosage": "",
                "effects_overdose": "",
                "expertise_advice": "",
                "how_to_use": "",
                "faqs": []
            },
            "createdAt": "2022-04-24T12:17:30.166Z",
            "updatedAt": "2022-04-24T12:17:30.166Z",
            "deletedAt": null
        },
        {
            "image": "https://pillbox-media.s3.ap-south-1.amazonaws.com/images/1650801787116-aistock.jpeg",
            "video": null,
            "id": 3,
            "uuid": "67a38c4e-166b-4a1c-a6ee-ff8d86783314",
            "name": "Demo Product ",
            "product_id": "",
            "price": 10,
            "discount": 1,
            "igst": 0,
            "hsn": "",
            "quantity": 10,
            "amount":1,
            "description": " description",
            "context": "",
            "composition": "",
            "packing_type": null,
            "packing_size": null,
            "schedule": null,
            "brand_id": 5,
            "status": "ACTIVE",
            "meta": {
                "usage": "",
                "about_salt": "",
                "mechanism_of_action": "",
                "pharmacokinets": "",
                "onset_of_action": "",
                "duration_of_action": "",
                "half_life": "",
                "side_effects": "",
                "contra_indications": "",
                "special_precautions": "",
                "pregnancy_related_information": "",
                "product_alchol_interaction": "",
                "old_age_related_information": "",
                "breast_feeding_related_information": "",
                "child_related_information": "",
                "indications": "",
                "interactions": "",
                "typical_dosage": "",
                "storage_requirements": "",
                "effects_mixed_dosage": "",
                "effects_overdose": "",
                "expertise_advice": "",
                "how_to_use": "",
                "faqs": []
            },
            "createdAt": "2022-04-24T12:03:07.523Z",
            "updatedAt": "2022-04-24T12:03:07.523Z",
            "deletedAt": null
        }],
    amount:1,
    total:0,
    isLoading:true,
}

const cartSlice=createSlice({
    name:'cart',
    initialState,
    reducers:{
        addtocart:(state,action)=>{
            state.cartItems.push(action.payload)
        },
        clearCart:(state)=>{
            state.cartItems=[]
        },
        removeItem:(state,action)=>{
            const itemId=action.payload;
            state.cartItems=state.cartItems.filter((item)=>
                item.uuid !== itemId);
        },
        calculateTotals:(state)=>{
            let amount=0;
            let total=0;
            state.cartItems.forEach((item)=>{
                amount+=item.amount
                total+=item.amount*item.price;
            })
            state.amount=amount;
            state.total=total;
        }
    }
})


export const{clearCart,removeItem,calculateTotals,addtocart}=cartSlice.actions;
export default cartSlice.reducer